<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'AlgoliaWooCommerceOrderSearchAdmin\\Tests' => array($vendorDir . '/algolia/algoliasearch-client-php/tests'),
    'AlgoliaWooCommerceOrderSearchAdmin' => array($vendorDir . '/algolia/algoliasearch-client-php/src'),
);
