<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'AlgoliaWooCommerceOrderSearchAdmin\\Index\\Tests\\' => array($vendorDir . '/algolia/index/tests'),
    'AlgoliaWooCommerceOrderSearchAdmin\\Index\\' => array($vendorDir . '/algolia/index/src'),
);
