<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'AlgoliaOrdersSearch\\AlgoliaIndex\\Tests\\' => array($vendorDir . '/rayrutjes/algolia-index/tests'),
    'AlgoliaOrdersSearch\\AlgoliaIndex\\' => array($vendorDir . '/rayrutjes/algolia-index/src'),
);
